#!/bin/bash
#
#$Info: ./doit - Script to run various performance runs. $
#
# ./doit -h will display the documentation

################################################################################
#
#  #    # ##### #     #####
#  #    # #     #     #    #
#  #    # #     #     #    #
#  ###### ##### #     #####
#  #    # #     #     #
#  #    # #     #     #
#  #    # ##### ##### #
#
################################################################################
# DOCUMENTATION
#-------------------------------------------------------------------------------
function Help() {
  perldoc $0
  cat >/dev/null <<.
=pod

=head1 NAME

B<doit> - Script to run various performance runs

=head1 SYNOPSIS

B<./doit> [OPTIONS] [VERSIONS]

=head1 DESCRIPTION

This script uses a specified simulator (default Mentor questa) to run
UVM objections performance testing. Default is to raise and lower objections
millions of times and report the overall CPU time.

=head1 OPTIONS

=over

=item B<-C> #

Number of times to repeat inner loop

=item B<-D> #

Number of agents to instantiate

=item B<-h>

Display this help.

=item B<-L> #

Number of levels of hierarchy above drivers

=item B<-P> 0|1

Propagate objections or not (affects 1.2 and above only)

=item B<-q>

Quiet mode to suppress unnecessary output.

=item B<-R> I<TRLEN>

Specify transaction length to use. This has
a special format using one hex digit for each
driver. Example: 3_2_1 means a length of 3ps
for driver 2, 2ps for driver 1, and 1ps for driver 0.
Unspecified drivers get a value of 1ps.

=item B<-S> questa|ius|vcs

Specify simulator to use.

=item B<-U> 0|1

Specify whether to use a full sequence (1) or a short 1ps sequence.

=item B<-t> I<TAG>

Specify a I<TAG> to include in log file name.

=item B<-p> #

Seconds to delay between simulations (minimum 5)

=item B<-v>

Verbose mode to expand explanatory output.

=back

=head1 VERSIONS

Supported versions are:

=over

=item 1.1b

=item 1.1c

=item 1.1d

=item 1.2

=item 1.2r

=back

=head1 COPYRIGHT

Copyright (C) 2014 Doulos Inc. All rights reserved.

=head1 AUTHOR

David C Black <david.black@doulos.com>

=cut

.
exit 0
}

################################################################################
#
#   ####   ####  ####   #####
#  #    # #    # #   #  #    
#  #      #    # #    # #    
#  #      #    # #    # #####
#  #      #    # #    # #    
#  #    # #    # #   #  #    
#   ####   ####  ####   #####
#
################################################################################
# CODE
#-------------------------------------------------------------------------------
export TAG

function analyze_uvm_objection_performance() {
  local R=""
  if [[ "$6" = "P=0" ]]; then P="r"; fi
  bin/header ${2}${P}${TAG}
  echo "------------------------------------------------------------------------------"
  echo "analyze_uvm_objection_performance ${1} ${2} ${3} ${4} ${5} ${6} ${7} ${8}"                | tee ${SIM}+uvm-${2}${R}${TAG}-log.txt
  echo "% env UVM_HOME=/eda/uvm/uvm-${2} make ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1" | tee -a ${SIM}+uvm-${2}${P}${TAG}-log.txt
  env UVM_HOME=/eda/uvm/uvm-${2} make ${1}_std V=${2} ${3} ${4} ${5} ${6} ${7} ${8} 2>&1          | tee -a ${SIM}+uvm-${2}${P}${TAG}-log.txt
}

################################################################################
function Doit() {
  local ALL="1.1b 1.1c 1.1d 1.2r 1.2"
  local LIST=""
  local verbose=0
  local pause=10
  local LEVELS=$LEVELS
  local AGENTS=$AGENTS
  local COUNTS=$COUNTS
  local RIPPLE=$RIPPLE
  local TR_LEN=$TR_LEN
  local USESEQ=$USESEQ
  local SIM=$SIM
  if [[ "$LEVELS" = "" ]]; then LEVELS=3; fi
  if [[ "$AGENTS" = "" ]]; then AGENTS=2; fi
  if [[ "$COUNTS" = "" ]]; then COUNTS=21000000; fi
  if [[ "$RIPPLE" = "" ]]; then RIPPLE=1; fi
  if [[ "$TR_LEN" = "" ]]; then TR_LEN=1; fi
  if [[ "$USESEQ" = "" ]]; then USESEQ=1; fi
  if [[ "$SIM"    = "" ]]; then SIM="questa"; fi

  while  [[ "${1}" =  -* ]];do
    if   [[ "${1}" = "-q" ]]; then verbose=0;
    elif [[ "${1}" = "-h"     ]]; then Help;
    elif [[ "${1}" = "-help"  ]]; then Help;
    elif [[ "${1}" = "--help" ]]; then Help;
    elif [[ "${1}" = "-p" ]]; then pause=${2};  shift;
    elif [[ "${1}" = "-t" ]]; then TAG=${2};    shift;
    elif [[ "${1}" = "-C" ]]; then COUNTS=${2}; shift;
    elif [[ "${1}" = "-D" ]]; then AGENTS=${2}; shift;
    elif [[ "${1}" = "-L" ]]; then LEVELS=${2}; shift;
    elif [[ "${1}" = "-P" ]]; then RIPPLE=${2}; shift;
    elif [[ "${1}" = "-S" ]]; then SIM=${2};    shift;
    elif [[ "${1}" = "-R" ]]; then TR_LEN=${2}; shift;
    elif [[ "${1}" = "-U" ]]; then USESEQ=${2}; shift;
    elif [[ "${1}" = "-v" ]]; then verbose=1;
    fi
    shift
  done
  while [[ $# != 0 ]]; do # Add user specified targets
    LIST="$LIST ${1}"
    shift
  done
  if [[ "$LIST" = "" ]]; then # Use default list
    LIST="$ALL"
  fi
  case $SIM in # Legal simulator target prefixes
    questa) ;;
    ius) ;;
    vcs) ;;
    *) echo "FATAL: Invalid simulator '$SIM' specified"; exit 1 ;;
  esac
  if [[ $pause -lt 10 ]]; then pause=10; fi # Minimum


  let first=1
  for V in $LIST; do
    # Pause between runs to allow clean interrupt
    if [[ $first = 0 && $pause != 0 ]]; then
      echo -n "Pausing $pause"
      let i=$pause
      while [[ $i -gt 0 ]]; do
        echo -n "."
        sleep 1;
        let i--
      done
      echo ""
    fi
    let first=0

    case "$V" in
      #     0                                 1    2    3         4         5         6
      1.1b) analyze_uvm_objection_performance $SIM 1.1b L=$LEVELS D=$AGENTS C=$COUNTS P=$RIPPLE U=$USESEQ R=$TR_LEN;;
      1.1c) analyze_uvm_objection_performance $SIM 1.1c L=$LEVELS D=$AGENTS C=$COUNTS P=$RIPPLE U=$USESEQ R=$TR_LEN;;
      1.1d) analyze_uvm_objection_performance $SIM 1.1d L=$LEVELS D=$AGENTS C=$COUNTS P=$RIPPLE U=$USESEQ R=$TR_LEN;;
      1.2r) analyze_uvm_objection_performance $SIM 1.2  L=$LEVELS D=$AGENTS C=$COUNTS P=0       U=$USESEQ R=$TR_LEN;;
      1.2 ) analyze_uvm_objection_performance $SIM 1.2  L=$LEVELS D=$AGENTS C=$COUNTS P=$RIPPLE U=$USESEQ R=$TR_LEN;;
      1.* ) analyze_uvm_objection_performance $SIM $V   L=$LEVELS D=$AGENTS C=$COUNTS P=$RIPPLE U=$USESEQ R=$TR_LEN;;
    esac
    echo ""
  done
  echo "------------------------------------------------------------------------------"
  echo "INFO: Don't forget to clean your messes..."
  echo "------------------------------------------------------------------------------"
  echo ""
}

################################################################################
Doit "$@"
